name: Version Check
on:
    pull_request:
        branches:
            - 'main'

jobs:
    check-version-bump:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Check version bump
              uses: bachmacintosh/need-npm-package-version-bump@v1

